const router=require('express').Router();
const authMiddleware=require('../middlewares/auth.middleware');
const allowRoles=require('../middlewares/role.middleware');
const c=require('../controllers/adminAnalytics.controller');
router.use(authMiddleware,allowRoles(1));
router.get('/overview',c.overview);
router.get('/user-growth',c.userGrowth);
router.get('/active-trend',c.activeTrend);
router.get('/role-distribution',c.roleDistribution);
router.get('/geography',c.geography);
router.get('/campus-targets',c.campusTargets);
router.get('/program-targets',c.programTargets);
router.get('/tryout-trend',c.tryoutTrend);
router.get('/score-distribution',c.scoreDistribution);
router.get('/subtests',c.subtests);
router.get('/study-progress',c.studyProgress);
router.get('/study-time',c.studyTime);
router.get('/accuracy-distribution',c.accuracyDistribution);
router.get('/activity-heatmap',c.activityHeatmap);
router.get('/platforms',c.platforms);
router.get('/leaderboard',c.leaderboard);
router.get('/most-improved',c.mostImproved);
router.get('/funnel',c.funnel);
router.get('/recent-activity',c.recentActivity);
router.get('/insights',c.insights);
module.exports=router;
