const rows = [
  ['first_step','First Step','Selesaikan materi pertama.','learning','common','BookOpen','materials_completed',1],
  ['bookworm','Bookworm','Selesaikan 10 materi aktif.','learning','rare','BookOpen', 'materials_completed',10],
  ['knowledge_seeker','Knowledge Seeker','Selesaikan 25 materi aktif.','learning','epic','BookOpen','materials_completed',25],
  ['material_master','Material Master','Selesaikan seluruh materi aktif pada satu subtes.','learning','epic','GraduationCap','material_master',1],
  ['first_practice','First Practice','Selesaikan sesi Practice pertama.','practice','common','Brain','practice_sessions',1],
  ['questions_100','100 Questions','Jawab 100 soal Practice.','practice','common','Target','practice_questions',100],
  ['questions_500','500 Questions','Jawab 500 soal Practice.','practice','rare','Target','practice_questions',500],
  ['questions_1000','1000 Questions','Jawab 1.000 soal Practice.','practice','epic','Target','practice_questions',1000],
  ['sharp_mind','Sharp Mind','Raih akurasi minimal 80% dalam sesi dengan sedikitnya 20 jawaban.','practice','rare','Brain','sharp_mind',1],
  ['perfect_run','Perfect Run','Jawab minimal 10 soal dalam satu sesi tanpa salah.','practice','rare','Star','perfect_run',1],
  ['fundamental_graduate','Fundamental Graduate','Selesaikan 3 sesi Fundamental, masing-masing minimal 10 jawaban dan akurasi 70%.','mastery','rare','GraduationCap','practice_level_1',3],
  ['intermediate_challenger','Intermediate Challenger','Selesaikan sesi Intermediate dengan minimal 10 jawaban dan akurasi 70%.','mastery','rare','Brain','practice_level_2',1],
  ['advanced_thinker','Advanced Thinker','Selesaikan sesi Advanced dengan minimal 10 jawaban dan akurasi 70%.','mastery','epic','Brain','practice_level_3',1],
  ['mastery_unlocked','Mastery Unlocked','Selesaikan sesi Mastery dengan minimal 10 jawaban dan akurasi 75%.','mastery','legendary','Crown','practice_level_4',1],
  ['streak_3','Getting Started','Belajar selama 3 hari berturut-turut.','consistency','common','Flame','study_streak',3],
  ['streak_7','One Week Strong','Belajar selama 7 hari berturut-turut.','consistency','rare','Flame','study_streak',7],
  ['streak_14','Two Week Warrior','Belajar selama 14 hari berturut-turut.','consistency','epic','Flame','study_streak',14],
  ['streak_30','Monthly Discipline','Belajar selama 30 hari berturut-turut.','consistency','epic','Flame','study_streak',30],
  ['planner','Planner','Buat Study Plan pertamamu.','consistency','common','CalendarCheck2','study_plan_created',1],
  ['on_schedule','On Schedule','Selesaikan 10 jadwal belajar.','consistency','rare','CalendarCheck2','study_plan_completed',10],
  ['weekly_champion','Weekly Champion','Selesaikan minimal 90% dari sedikitnya 5 jadwal dalam satu minggu.','consistency','epic','CalendarCheck2','weekly_champion',1],
  ['first_recap','First Recap','Tambahkan rekap tryout eksternal pertama.','tryout','common','Trophy','tryout_recaps',1],
  ['getting_better','Getting Better','Skor meningkat dalam 3 rekap berturut-turut.','tryout','rare','TrendingUp','tryout_improvement_3',1],
  ['personal_best','Personal Best','Catat skor baru yang melampaui seluruh rekap sebelumnya.','tryout','rare','Medal','personal_best',1],
  ['club_700','700 Club','Raih best score tryout eksternal minimal 700.','tryout','epic','Trophy','best_tryout_score',700],
  ['club_750','750 Club','Raih best score tryout eksternal minimal 750.','tryout','legendary','Trophy','best_tryout_score',750],
  ['dream_set','Dream Set','Tetapkan target kampus dan program studi.','special','common','GraduationCap','target_set',1],
  ['getting_closer','Getting Closer','Capai selisih paling banyak 50 poin dari target score.','special','rare','Target','target_gap',50],
  ['target_reached','Target Score Tercapai','Best score mencapai target score yang kamu tetapkan.','special','epic','Target','target_reached',1],
  ['foundation_complete','Foundation Complete','Selesaikan Tahap 1 Roadmap.','roadmap','common','CircleCheck','roadmap_stage_1',1],
  ['concept_builder','Concept Builder','Selesaikan Tahap 2 Roadmap.','roadmap','rare','BookOpen','roadmap_stage_2',1],
  ['practice_warrior','Practice Warrior','Selesaikan Tahap 3 Roadmap.','roadmap','rare','Brain','roadmap_stage_3',1],
  ['evaluation_ready','Evaluation Ready','Selesaikan Tahap 4 Roadmap.','roadmap','epic','Trophy','roadmap_stage_4',1],
  ['roadmap_finisher','Roadmap Finisher','Selesaikan Tahap 5 Roadmap.','roadmap','legendary','Crown','roadmap_stage_5',1],
  ['pk_specialist','PK Specialist','Raih akurasi Practice PK 80% dari minimal 50 jawaban.','mastery','epic','Brain','subtest_accuracy_PK',80],
  ['literacy_specialist','Literacy Specialist','Raih akurasi Practice LBI atau LBE 80% dari minimal 50 jawaban.','mastery','epic','BookOpen','literacy_specialist',80],
  ['math_specialist','Math Specialist','Raih akurasi Practice PM 80% dari minimal 50 jawaban.','mastery','epic','Brain','subtest_accuracy_PM',80],
];
const xp = { common: 50, rare: 100, epic: 250, legendary: 500 };
module.exports = rows.map(([code,name,description,category,rarity,icon,condition_type,condition_value],index) => ({ code,name,description,category,rarity,icon,condition_type,condition_value,xp_reward:xp[rarity],is_active:true,sort_order:index+1 }));
